const sql = require('./netlify/functions/utils/db'); // Menggunakan koneksi yang sama dengan functions
const bcrypt = require('bcryptjs');

// --- DATA UNTUK SEEDING ---
const adminUser = {
    username: 'admin',
    password: 'password123'
};

// Ambil data film dari seeder sebelumnya (pastikan field 'type' ada)
const moviesData = [
    // 50 Film (Marvel, DC, Indonesia, Original)
    { "imdb_id": "tt0848228", "title": "The Avengers", "year": "2012", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", "plot": "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.", "director": "Joss Whedon", "actors": "Robert Downey Jr., Chris Evans, Scarlett Johansson", "genre": "Action, Adventure, Sci-Fi", "runtime": "143 min", "trailer_url": "https://www.youtube.com/embed/eOrNdBpGMv8" },
    { "imdb_id": "tt0468569", "title": "The Dark Knight", "year": "2008", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg", "plot": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", "director": "Christopher Nolan", "actors": "Christian Bale, Heath Ledger, Aaron Eckhart", "genre": "Action, Crime, Drama", "runtime": "152 min", "trailer_url": "https://www.youtube.com/embed/EXeTwQWrcwY" },
    { "imdb_id": "tt1375666", "title": "Inception", "year": "2010", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg", "plot": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", "director": "Christopher Nolan", "actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page", "genre": "Action, Adventure, Sci-Fi", "runtime": "148 min", "trailer_url": "https://www.youtube.com/embed/YoHD9XEInc0" },
    { "imdb_id": "tt0133093", "title": "The Matrix", "year": "1999", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", "plot": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", "director": "Lana Wachowski, Lilly Wachowski", "actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss", "genre": "Action, Sci-Fi", "runtime": "136 min", "trailer_url": "https://www.youtube.com/embed/vKQi3bBA1y8" },
    { "imdb_id": "tt0110912", "title": "Pulp Fiction", "year": "1994", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "plot": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", "director": "Quentin Tarantino", "actors": "John Travolta, Uma Thurman, Samuel L. Jackson", "genre": "Crime, Drama", "runtime": "154 min", "trailer_url": "https://www.youtube.com/embed/s7EdQ4FqbhY" },
    { "imdb_id": "tt0120737", "title": "The Lord of the Rings: The Fellowship of the Ring", "year": "2001", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg", "plot": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.", "director": "Peter Jackson", "actors": "Elijah Wood, Ian McKellen, Orlando Bloom", "genre": "Action, Adventure, Drama", "runtime": "178 min", "trailer_url": "https://www.youtube.com/embed/V75dMMIW2B4" },
    { "imdb_id": "tt0109830", "title": "Forrest Gump", "year": "1994", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "plot": "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.", "director": "Robert Zemeckis", "actors": "Tom Hanks, Robin Wright, Gary Sinise", "genre": "Drama, Romance", "runtime": "142 min", "trailer_url": "https://www.youtube.com/embed/bLvqoHBptjg" },
    { "imdb_id": "tt1345836", "title": "The Dark Knight Rises", "year": "2012", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg", "plot": "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.", "director": "Christopher Nolan", "actors": "Christian Bale, Tom Hardy, Anne Hathaway", "genre": "Action, Adventure", "runtime": "164 min", "trailer_url": "https://www.youtube.com/embed/g8evyE9TuYk" },
    { "imdb_id": "tt2911666", "title": "John Wick", "year": "2014", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_SX300.jpg", "plot": "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took his car.", "director": "Chad Stahelski, David Leitch", "actors": "Keanu Reeves, Michael Nyqvist, Alfie Allen", "genre": "Action, Crime, Thriller", "runtime": "101 min", "trailer_url": "https://www.youtube.com/embed/C0BMx-qxsP4" },
    { "imdb_id": "tt7286456", "title": "Joker", "year": "2019", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWI0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", "plot": "A mentally troubled comedian embarks on a downward spiral that leads to the creation of an iconic villain.", "director": "Todd Phillips", "actors": "Joaquin Phoenix, Robert De Niro, Zazie Beetz", "genre": "Crime, Drama, Thriller", "runtime": "122 min", "trailer_url": "https://www.youtube.com/embed/zAGVQLHvwOY" },
    { "imdb_id": "tt0114369", "title": "Se7en", "year": "1995", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", "plot": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.", "director": "David Fincher", "actors": "Morgan Freeman, Brad Pitt, Kevin Spacey", "genre": "Crime, Drama, Mystery", "runtime": "127 min", "trailer_url": "https://www.youtube.com/embed/znmZoVkCjpI" },
    { "imdb_id": "tt0108052", "title": "Schindler's List", "year": "1993", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", "plot": "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.", "director": "Steven Spielberg", "actors": "Liam Neeson, Ralph Fiennes, Ben Kingsley", "genre": "Biography, Drama, History", "runtime": "195 min", "trailer_url": "https://www.youtube.com/embed/gG22XNhtnoY" },
    { "imdb_id": "tt0167260", "title": "The Lord of the Rings: The Return of the King", "year": "2003", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "plot": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", "director": "Peter Jackson", "actors": "Elijah Wood, Viggo Mortensen, Ian McKellen", "genre": "Action, Adventure, Drama", "runtime": "201 min", "trailer_url": "https://www.youtube.com/embed/r5X-hFf6Bwo" },
    { "imdb_id": "tt0068646", "title": "The Godfather", "year": "1972", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", "director": "Francis Ford Coppola", "actors": "Marlon Brando, Al Pacino, James Caan", "genre": "Crime, Drama", "runtime": "175 min", "trailer_url": "https://www.youtube.com/embed/sY1S34973zA" },
    { "imdb_id": "tt0137523", "title": "Fight Club", "year": "1999", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg", "plot": "An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more.", "director": "David Fincher", "actors": "Brad Pitt, Edward Norton, Meat Loaf", "genre": "Drama", "runtime": "139 min", "trailer_url": "https://www.youtube.com/embed/SUXWAEX2jlg" },
    { "imdb_id": "tt0120815", "title": "Saving Private Ryan", "year": "1998", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg", "plot": "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.", "director": "Steven Spielberg", "actors": "Tom Hanks, Matt Damon, Tom Sizemore", "genre": "Drama, War", "runtime": "169 min", "trailer_url": "https://www.youtube.com/embed/RYExstiQlLc" },
    { "imdb_id": "tt0816692", "title": "Interstellar", "year": "2014", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", "plot": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "director": "Christopher Nolan", "actors": "Matthew McConaughey, Anne Hathaway, Jessica Chastain", "genre": "Adventure, Drama, Sci-Fi", "runtime": "169 min", "trailer_url": "https://www.youtube.com/embed/zSWdZVtXT7E" },
    { "imdb_id": "tt0120689", "title": "The Green Mile", "year": "1999", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg", "plot": "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.", "director": "Frank Darabont", "actors": "Tom Hanks, Michael Clarke Duncan, David Morse", "genre": "Crime, Drama, Fantasy", "runtime": "189 min", "trailer_url": "https://www.youtube.com/embed/Ki4haFrqSrw" },
    { "imdb_id": "tt0111161", "title": "The Shawshank Redemption", "year": "1994", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg", "plot": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", "director": "Frank Darabont", "actors": "Tim Robbins, Morgan Freeman, Bob Gunton", "genre": "Drama", "runtime": "142 min", "trailer_url": "https://www.youtube.com/embed/6hB3S9bIaco" },
    { "imdb_id": "tt0102926", "title": "The Silence of the Lambs", "year": "1991", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", "plot": "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.", "director": "Jonathan Demme", "actors": "Jodie Foster, Anthony Hopkins, Lawrence A. Bonney", "genre": "Crime, Drama, Thriller", "runtime": "118 min", "trailer_url": "https://www.youtube.com/embed/W6Mm8Sbe__o" },
    
    // 10 Film Marvel
    { "imdb_id": "tt0371746", "title": "Iron Man", "year": "2008", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg", "plot": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.", "director": "Jon Favreau", "actors": "Robert Downey Jr., Gwyneth Paltrow, Terrence Howard", "genre": "Action, Adventure, Sci-Fi", "runtime": "126 min", "trailer_url": "https://www.youtube.com/embed/8hYlB38asDY" },
    { "imdb_id": "tt0458339", "title": "Captain America: The First Avenger", "year": "2011", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTYzOTc2NzU3N15BMl5BanBnXkFtZTcwNjY3MDE3NQ@@._V1_SX300.jpg", "plot": "Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a 'Super-Soldier serum'.", "director": "Joe Johnston", "actors": "Chris Evans, Hugo Weaving, Samuel L. Jackson", "genre": "Action, Adventure, Sci-Fi", "runtime": "124 min", "trailer_url": "https://www.youtube.com/embed/JerVrbLldXw" },
    { "imdb_id": "tt0800369", "title": "Thor", "year": "2011", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BOGE4NzU1YTAtNzA3Mi00ZTA2LTg2YmYtMDJmMThiMjlkYjg2XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg", "plot": "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans on Earth...", "director": "Kenneth Branagh", "actors": "Chris Hemsworth, Anthony Hopkins, Natalie Portman", "genre": "Action, Adventure, Fantasy", "runtime": "115 min", "trailer_url": "https://www.youtube.com/embed/JOddp-nlNvQ" },
    { "imdb_id": "tt2015381", "title": "Guardians of the Galaxy", "year": "2014", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNDIzMTk4NDYtMjg5OS00ZGI0LWJhM2YtNzQ5MGM2N2QzMWM4XkEyXkFqcGdeQXVyMTI5NzUyMTIz._V1_SX300.jpg", "plot": "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.", "director": "James Gunn", "actors": "Chris Pratt, Vin Diesel, Bradley Cooper", "genre": "Action, Adventure, Comedy", "runtime": "121 min", "trailer_url": "https://www.youtube.com/embed/d96cjJhvlMA" },
    { "imdb_id": "tt1211837", "title": "Doctor Strange", "year": "2016", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SX300.jpg", "plot": "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.", "director": "Scott Derrickson", "actors": "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams", "genre": "Action, Adventure, Fantasy", "runtime": "115 min", "trailer_url": "https://www.youtube.com/embed/HSzx-zryEgM" },
    { "imdb_id": "tt2250912", "title": "Spider-Man: Homecoming", "year": "2017", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNTk4ODQ1MzgzNl5BMl5BanBnXkFtZTgwMTMyMzM4MTI@._V1_SX300.jpg", "plot": "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man.", "director": "Jon Watts", "actors": "Tom Holland, Michael Keaton, Robert Downey Jr.", "genre": "Action, Adventure, Sci-Fi", "runtime": "133 min", "trailer_url": "https://www.youtube.com/embed/n9DwoQ7HWvI" },
    { "imdb_id": "tt1825683", "title": "Black Panther", "year": "2018", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg", "plot": "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future.", "director": "Ryan Coogler", "actors": "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o", "genre": "Action, Adventure, Sci-Fi", "runtime": "134 min", "trailer_url": "https://www.youtube.com/embed/xjDjIsc3lY" },
    { "imdb_id": "tt4154664", "title": "Captain Marvel", "year": "2019", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_SX300.jpg", "plot": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war.", "director": "Anna Boden, Ryan Fleck", "actors": "Brie Larson, Samuel L. Jackson, Ben Mendelsohn", "genre": "Action, Adventure, Sci-Fi", "runtime": "123 min", "trailer_url": "https://www.youtube.com/embed/Z1BCujX3pw8" },
    { "imdb_id": "tt9376612", "title": "Shang-Chi and the Legend of the Ten Rings", "year": "2021", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNTliYjlkMDQtMjFlNS00NjgzLWFmMWEtYmM2Mzc2Zjg3ZjEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", "plot": "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past...", "director": "Destin Daniel Cretton", "actors": "Simu Liu, Awkwafina, Tony Leung Chiu-wai", "genre": "Action, Adventure, Fantasy", "runtime": "132 min", "trailer_url": "https://www.youtube.com/embed/8YjFbMbfXaQ" },
    { "imdb_id": "tt10872600", "title": "Spider-Man: No Way Home", "year": "2021", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg", "plot": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong...", "director": "Jon Watts", "actors": "Tom Holland, Zendaya, Benedict Cumberbatch", "genre": "Action, Adventure, Fantasy", "runtime": "148 min", "trailer_url": "https://www.youtube.com/embed/JfVOs4VSpmA" },

    // 10 Film DC
    { "imdb_id": "tt0078346", "title": "Superman", "year": "1978", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMzA0YWMwMTUtMTgxOC00YjA5LGI2YjEtMWQ4Y2ZhYmU2NWIwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg", "plot": "An alien orphan is sent from his dying planet to Earth, where he grows up to become his adoptive home's first and greatest superhero.", "director": "Richard Donner", "actors": "Christopher Reeve, Margot Kidder, Gene Hackman", "genre": "Action, Adventure, Sci-Fi", "runtime": "143 min", "trailer_url": "https://www.youtube.com/embed/pUwxH4SM9Rg" },
    { "imdb_id": "tt0096895", "title": "Batman", "year": "1989", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg", "plot": "The Dark Knight of Gotham City begins his war on crime with his first major enemy being the Joker.", "director": "Tim Burton", "actors": "Michael Keaton, Jack Nicholson, Kim Basinger", "genre": "Action, Adventure", "runtime": "126 min", "trailer_url": "https://www.youtube.com/embed/dgC9Q0uhX70" },
    { "imdb_id": "tt0372784", "title": "Batman Begins", "year": "2005", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00YTMwLWI5YjYtYzYzNGE5YjI3MzA4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "plot": "After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.", "director": "Christopher Nolan", "actors": "Christian Bale, Michael Caine, Ken Watanabe", "genre": "Action, Crime, Drama", "runtime": "140 min", "trailer_url": "https://www.youtube.com/embed/neY2xVmOfUM" },
    { "imdb_id": "tt0770828", "title": "Man of Steel", "year": "2013", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTk5ODk1NDkxMF5BMl5BanBnXkFtZTcwNTA5OTY0OQ@@._V1_SX300.jpg", "plot": "An alien child is evacuated from his dying world and sent to Earth to live among humans...", "director": "Zack Snyder", "actors": "Henry Cavill, Amy Adams, Michael Shannon", "genre": "Action, Adventure, Sci-Fi", "runtime": "143 min", "trailer_url": "https://www.youtube.com/embed/T6DJcgm3wNY" },
    { "imdb_id": "tt0451279", "title": "Wonder Woman", "year": "2017", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTYzODQzYjQtNTczNC00MzZhLTg1ZWYtZDUxYmQ3ZGE0Njk3XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg", "plot": "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war.", "director": "Patty Jenkins", "actors": "Gal Gadot, Chris Pine, Robin Wright", "genre": "Action, Adventure, Fantasy", "runtime": "141 min", "trailer_url": "https://www.youtube.com/embed/1Q8fG0TtVAY" },
    { "imdb_id": "tt1477834", "title": "Aquaman", "year": "2018", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BOTk5ODg0OTU5M15BMl5BanBnXkFtZTgwMDQ3MDY3NjM@._V1_SX300.jpg", "plot": "Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war...", "director": "James Wan", "actors": "Jason Momoa, Amber Heard, Willem Dafoe", "genre": "Action, Adventure, Fantasy", "runtime": "143 min", "trailer_url": "https://www.youtube.com/embed/WDkg3h8PCVU" },
    { "imdb_id": "tt0448115", "title": "Shazam!", "year": "2019", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BYTE0Yjc1NzUtMjFjMC00Y2VjLWI0YWUtYTM0YWQ4OTE3N2Q1XkEyXkFqcGdeQXVyNjc3OTE4Nzk@._V1_SX300.jpg", "plot": "A newly fostered young boy in search of his mother instead finds unexpected superpowers...", "director": "David F. Sandberg", "actors": "Zachary Levi, Mark Strong, Asher Angel", "genre": "Action, Adventure, Comedy", "runtime": "132 min", "trailer_url": "https://www.youtube.com/embed/go6GEIrcvFY" },
    { "imdb_id": "tt6334354", "title": "The Suicide Squad", "year": "2021", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BNGM3YzdlOWYtNjViZS00MTE2LWE1MWUtZmE2ZTQzNTU2MmMyXkEyXkFqcGdeQXVyMTM1MTE1NDM1._V1_SX300.jpg", "plot": "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of cons at Belle Reve prison join the Task Force X.", "director": "James Gunn", "actors": "Margot Robbie, Idris Elba, John Cena", "genre": "Action, Adventure, Comedy", "runtime": "132 min", "trailer_url": "https://www.youtube.com/embed/eg5ciqQzmK0" },
    { "imdb_id": "tt1877830", "title": "The Batman", "year": "2022", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg", "plot": "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate...", "director": "Matt Reeves", "actors": "Robert Pattinson, Zoë Kravitz, Jeffrey Wright", "genre": "Action, Crime, Drama", "runtime": "176 min", "trailer_url": "https://www.youtube.com/embed/mqqft2x_Aa4" },
    { "imdb_id": "tt6443346", "title": "Black Adam", "year": "2022", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BYzZkYjM2DEtMGQzMi00ZGY4LTk3Y2YtMzA2ZmM1NTI2YmU4XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SX300.jpg", "plot": "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods, Black Adam is freed...", "director": "Jaume Collet-Serra", "actors": "Dwayne Johnson, Aldis Hodge, Pierce Brosnan", "genre": "Action, Adventure, Fantasy", "runtime": "125 min", "trailer_url": "https://www.youtube.com/embed/X0tOpBuYasI" },

    // 10 Film Indonesia
    { "imdb_id": "tt1193138", "title": "Laskar Pelangi", "year": "2008", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMjE5NDg0Mjc5Ml5BMl5BanBnXkFtZTcwOTE4MTk3MQ@@._V1_SX300.jpg", "plot": "Sekelompok 10 siswa berjuang dengan kemiskinan dan mengembangkan harapan untuk masa depan di Desa Gantong...", "director": "Riri Riza", "actors": "Zulfanny, Ferdian, Verrys Yamarno", "genre": "Drama", "runtime": "125 min", "trailer_url": "https://www.youtube.com/embed/d3_n5D22-6M" },
    { "imdb_id": "tt1899353", "title": "The Raid: Redemption", "year": "2011", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BYjE1YjQ2YjUtYjM5YS00OTk0LTg5Y2MtY2I5NjE3M2YyMWM1XkEyXkFqcGdeQXVyMTI3Mjc2MDU5._V1_SX300.jpg", "plot": "Sebuah tim S.W.A.T. terperangkap di sebuah rumah susun yang dijalankan oleh seorang mafia kejam...", "director": "Gareth Evans", "actors": "Iko Uwais, Joe Taslim, Donny Alamsyah", "genre": "Action, Thriller", "runtime": "101 min", "trailer_url": "https://www.youtube.com/embed/m6Q7KnXpNOg" },
    { "imdb_id": "tt7076834", "title": "Pengabdi Setan", "year": "2017", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTQ2OTI2MzYwN15BMl5BanBnXkFtZTgwNTg3MDUxNjM@._V1_SX300.jpg", "plot": "Setelah meninggal karena penyakit aneh yang dideritanya selama 3 tahun, seorang ibu kembali ke rumah untuk menjemput anak-anaknya.", "director": "Joko Anwar", "actors": "Tara Basro, Bront Palarae, Endy Arfian", "genre": "Drama, Horror, Mystery", "runtime": "107 min", "trailer_url": "https://www.youtube.com/embed/0hSptYxWB3E" },
    { "imdb_id": "tt5187312", "title": "Ada Apa dengan Cinta? 2", "year": "2016", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMTYxODg5OTYtY2ExNC00ZmY0LTg3ZjQtYmY1YjgwY2Y4NzYxXkEyXkFqcGdeQXVyNzI5NjYzOTA@._V1_SX300.jpg", "plot": "Cinta dan Rangga, yang terpisah 14 tahun lalu tanpa penjelasan apa pun, kini bertemu kembali di Yogyakarta.", "director": "Riri Riza", "actors": "Dian Sastrowardoyo, Nicholas Saputra, Titi Kamal", "genre": "Drama, Romance", "runtime": "124 min", "trailer_url": "https://www.youtube.com/embed/Qfccg2eY_1U" },
    { "imdb_id": "tt9231290", "title": "Gundala", "year": "2019", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMjBjY2Q2YWEtOTY0OC00M2QzLWFhYjEtY2M2ODU5Mjc5YTMwXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg", "plot": "Pahlawan super terkemuka Indonesia dan alter egonya, Sancaka, memasuki dunia sinematik untuk melawan Pengkor yang jahat...", "director": "Joko Anwar", "actors": "Abimana Aryasatya, Tara Basro, Bront Palarae", "genre": "Action, Adventure, Sci-Fi", "runtime": "123 min", "trailer_url": "https://www.youtube.com/embed/2B02G1IVEpE" },
    { "imdb_id": "tt8093158", "title": "Dilan 1990", "year": "2018", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMzE0Mjg2MzYtODY3MS00YjQ0LWI4MDItZTVmYTVmYjYyYjU0XkEyXkFqcGdeQXVyNzI5NjYzOTA@._V1_SX300.jpg", "plot": "Milea (Vanesha Prescilla) bertemu dengan Dilan (Iqbaal Ramadhan) di sebuah SMA di Bandung pada tahun 1990...", "director": "Fajar Bustomi, Pidi Baiq", "actors": "Iqbaal Ramadhan, Vanesha Prescilla, Ira Wibowo", "genre": "Drama, Romance", "runtime": "110 min", "trailer_url": "https://www.youtube.com/embed/X_b6J0A_4_4" },
    { "imdb_id": "tt6863176", "title": "Marlina si Pembunuh dalam Empat Babak", "year": "2017", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMjE1MjYyNjQ0Nl5BMl5BanBnXkFtZTgwNTk5OTU4MzI@._V1_SX300.jpg", "plot": "Seorang janda muda melawan sekelompok perampok yang datang untuk mencuri ternaknya.", "director": "Mouly Surya", "actors": "Marsha Timothy, Dea Panendra, Yoga Pratama", "genre": "Drama, Thriller, Western", "runtime": "93 min", "trailer_url": "https://www.youtube.com/embed/a-Y32a51_P4" },
    { "imdb_id": "tt10633884", "title": "Perempuan Tanah Jahanam", "year": "2019", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BYzEwOGI0ZWItY2ZiOS00N2YyLWIyY2YtY2I5NjE3M2YyMWM1XkEyXkFqcGdeQXVyMTI3Mjc2MDU5._V1_SX300.jpg", "plot": "Maya bersama sahabatnya, Dini, mencoba bertahan hidup di kota tanpa keluarga. Dia menyadari bahwa dia mungkin akan mewarisi properti...", "director": "Joko Anwar", "actors": "Tara Basro, Ario Bayu, Marissa Anita", "genre": "Horror, Mystery, Thriller", "runtime": "107 min", "trailer_url": "https://www.youtube.com/embed/1h9Yf2f65yA" },
    { "imdb_id": "tt11231616", "title": "KKN di Desa Penari", "year": "2022", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BYzNhYjU5ZmItY2E5OS00NGRjLTk4YzYtNjU0OTQ0OTYyMWM1XkEyXkFqcGdeQXVyNzI5NjYzOTA@._V1_SX300.jpg", "plot": "Sekelompok mahasiswa harus meninggalkan lokasi KKN mereka di sebuah desa terpencil setelah insiden fatal...", "director": "Awi Suryadi", "actors": "Tissa Biani Azzahra, Achmad Megantara, Calvin Jeremy", "genre": "Horror, Mystery", "runtime": "130 min", "trailer_url": "https://www.youtube.com/embed/wS23-p3k9cQ" },
    { "imdb_id": "tt19864802", "title": "Ngeri-Ngeri Sedap", "year": "2022", "type": "movie", "poster": "https://m.media-amazon.com/images/M/MV5BMjI3Mjc2MDU5M15BMl5BanBnXkFtZTgwMDQ3MDY3NjM@._V1_SX300.jpg", "plot": "Sepasang suami istri dengan tiga anak yang sudah lama merantau dan tidak pernah berkunjung, berpura-pura akan bercerai...", "director": "Bene Dion Rajagukguk", "actors": "Arswendy Bening Swara, Tika Panggabean, Boris Bokir", "genre": "Comedy, Drama, Family", "runtime": "114 min", "trailer_url": "https://www.youtube.com/embed/z3w2K0yS5P0" },

    // 10 TV Series Marvel
    { "imdb_id": "tt9140560", "title": "WandaVision", "year": "2021", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BNGE0M2VkMmQtYThmZC00YjllLThlZDctODQ3Y2I0NGYyYmQ5XkEyXkFqcGdeQXVyMTI5MzA5MjA1._V1_SX300.jpg", "plot": "Blends the style of classic sitcoms with the MCU, in which Wanda Maximoff and Vision - two super-powered beings living their ideal suburban lives - begin to suspect that everything is not as it seems.", "director": "N/A", "actors": "Elizabeth Olsen, Paul Bettany, Kathryn Hahn", "genre": "Action, Comedy, Drama", "runtime": "358 min", "trailer_url": "https://www.youtube.com/embed/sj9J2ecsSpo" },
    { "imdb_id": "tt9140554", "title": "Loki", "year": "2021–", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BNTkwOTE1ZDYtODQ3Yy00YTYwLTg0YWQtYmVkNmFjNGZlYmRiXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg", "plot": "The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of 'Avengers: Endgame'.", "director": "N/A", "actors": "Tom Hiddleston, Owen Wilson, Gugu Mbatha-Raw", "genre": "Action, Adventure, Fantasy", "runtime": "N/A", "trailer_url": "https://www.youtube.com/embed/nW948Va-l10" },
    { "imdb_id": "tt9208876", "title": "The Falcon and the Winter Soldier", "year": "2021", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BODNiODVmYjItM2MyMC00ZWQyLTgyMGYtNzJjMmVmZTY2OTJjXkEyXkFqcGdeQXVyNzk3NDUzNTc@._V1_SX300.jpg", "plot": "Following the events of 'Avengers: Endgame,' Sam Wilson/Falcon and Bucky Barnes/Winter Soldier team up in a global adventure that tests their abilities -- and their patience.", "director": "N/A", "actors": "Anthony Mackie, Sebastian Stan, Wyatt Russell", "genre": "Action, Adventure, Drama", "runtime": "305 min", "trailer_url": "https://www.youtube.com/embed/IWBsDaFWyTE" },
    { "imdb_id": "tt10231224", "title": "Hawkeye", "year": "2021", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BZGRjYjNmYmQtZTI4NS00MDcwLWIxMjYtNzVlY2UwYTBmYjcyXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_SX300.jpg", "plot": "Series based on the Marvel Comics superhero Hawkeye, centering on the adventures of Young Avenger, Kate Bishop, who took on the role after the original Avenger, Clint Barton.", "director": "N/A", "actors": "Jeremy Renner, Hailee Steinfeld, Florence Pugh", "genre": "Action, Adventure, Crime", "runtime": "317 min", "trailer_url": "https://www.youtube.com/embed/5VYb3B1ETlk" },
    { "imdb_id": "tt10234724", "title": "Moon Knight", "year": "2022", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BYTc5OWNhYjktMThlOS00ODUxLTgwNDQtZjdjYjkyM2IwZTZlXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_SX300.jpg", "plot": "A former U.S. Marine, struggling with dissociative identity disorder, is granted the powers of an Egyptian moon god.", "director": "N/A", "actors": "Oscar Isaac, Ethan Hawke, May Calamawy", "genre": "Action, Adventure, Drama", "runtime": "286 min", "trailer_url": "https://www.youtube.com/embed/x7Krla_UxRg" },
    { "imdb_id": "tt10857164", "title": "Ms. Marvel", "year": "2022", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BZmQ3OTZkNDUtNTU0Mi00ZjE5LTgyMjEtN2Q5NzBiNGJmMDZkXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg", "plot": "Kamala Khan, a great student, an avid gamer and a voracious fan-fic scribe, feels she doesn't fit in at school and sometimes even at home.", "director": "N/A", "actors": "Iman Vellani, Matt Lintz, Yasmeen Fletcher", "genre": "Action, Adventure, Comedy", "runtime": "262 min", "trailer_url": "https://www.youtube.com/embed/m9EX0f6V11A" },
    { "imdb_id": "tt10857160", "title": "She-Hulk: Attorney at Law", "year": "2022", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BMjU4MTkxNzktNzUyYy00NDM2LWE5NGYtOTUwYjgsNmNkMjJkMTIzNTU2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", "plot": "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.", "director": "N/A", "actors": "Tatiana Maslany, Mark Ruffalo, Ginger Gonzaga", "genre": "Action, Adventure, Comedy", "runtime": "35 min", "trailer_url": "https://www.youtube.com/embed/u7JsKhI2An0" },
    { "imdb_id": "tt3322312", "title": "Daredevil", "year": "2015–2018", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BODcwOTg2MDE3NF5BMl5BanBnXkFtZTgwNTUyNTY1NzE@._V1_SX300.jpg", "plot": "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.", "director": "N/A", "actors": "Charlie Cox, Vincent D'Onofrio, Deborah Ann Woll", "genre": "Action, Crime, Drama", "runtime": "54 min", "trailer_url": "https://www.youtube.com/embed/jAy6NJ_D5vU" },
    { "imdb_id": "tt2372162", "title": "Jessica Jones", "year": "2015–2019", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BMTkxMDk5MDQyOV5BMl5BanBnXkFtZTgwNzg3ODU3OFE@._V1_SX300.jpg", "plot": "Following the tragic end of her brief superhero career, Jessica Jones tries to rebuild her life as a private investigator.", "director": "N/A", "actors": "Krysten Ritter, Rachael Taylor, Eka Darville", "genre": "Action, Crime, Drama", "runtime": "56 min", "trailer_url": "https://www.youtube.com/embed/nWHUjuJ8Gtw" },
    { "imdb_id": "tt5675620", "title": "The Punisher", "year": "2017–2019", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BMTExODIwOTUxNzFeQTJeQWpwZ15BbWU4MDE5MDA0MTMy._V1_SX300.jpg", "plot": "After the murder of his family, Marine veteran Frank Castle becomes the vigilante known as 'The Punisher'.", "director": "N/A", "actors": "Jon Bernthal, Amber Rose Revah, Ben Barnes", "genre": "Action, Crime, Drama", "runtime": "53 min", "trailer_url": "https://www.youtube.com/embed/s4QV6OZdmWY" },

    // 10 TV Series DC
    { "imdb_id": "tt3107288", "title": "The Flash", "year": "2014–2023", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BMDIzNzYwNTctZWY4Mi00YjQ2LWI5YWYtMzFkN2FmNWQ2YjY5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", "plot": "After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed.", "director": "N/A", "actors": "Grant Gustin, Candice Patton, Danielle Panabaker", "genre": "Action, Adventure, Drama", "runtime": "43 min", "trailer_url": "https://www.youtube.com/embed/Yj0l7iGKh8g" },
    { "imdb_id": "tt2193021", "title": "Arrow", "year": "2012–2020", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BMTI0NTMwMDgtYmYyYy00Y2VmLWI1MTEtM2Q2YjY4YjA0MjliXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SX300.jpg", "plot": "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea.", "director": "N/A", "actors": "Stephen Amell, Katie Cassidy, David Ramsey", "genre": "Action, Adventure, Crime", "runtime": "42 min", "trailer_url": "https://www.youtube.com/embed/Xqg9iTch_A" },
    { "imdb_id": "tt3749900", "title": "Gotham", "year": "2014–2019", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BMTU5NjQ2MTU4NV5BMl5BanBnXkFtZTgwOTYxNTAwNzE@._V1_SX300.jpg", "plot": "The story behind Detective James Gordon's rise to prominence in Gotham City in the years before Batman's arrival.", "director": "N/A", "actors": "Ben McKenzie, Jada Pinkett Smith, Donal Logue", "genre": "Action, Crime, Drama", "runtime": "44 min", "trailer_url": "https://www.youtube.com/embed/0d1zpt6k5OI" },
    { "imdb_id": "tt1043813", "title": "Titans", "year": "2018–2023", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BOGE4YjJhNWEtMTNlMi00MTliLThmYzYtMWMwM2E2N2VjZDFiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", "plot": "A team of young superheroes combat evil and other perils.", "director": "N/A", "actors": "Brenton Thwaites, Anna Diop, Ryan Potter", "genre": "Action, Adventure, Crime", "runtime": "45 min", "trailer_url": "https://www.youtube.com/embed/QIYzdBAjGEA" },
    { "imdb_id": "tt8416494", "title": "Doom Patrol", "year": "2019–2023", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BNTA0N2Q3YjctMWVlYy00ODQ1LWEyNzItY2Q5YmMyNzA0YjEwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", "plot": "The adventures of an idealized group of people with superhuman abilities.", "director": "N/A", "actors": "Diane Guerrero, April Bowlby, Matt Bomer", "genre": "Action, Adventure, Comedy", "runtime": "60 min", "trailer_url": "https://www.youtube.com/embed/6tTM9R7v3Ww" },
    { "imdb_id": "tt13146488", "title": "Peacemaker", "year": "2022–", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BODk2NjAyOWMtZmQ3Zi00ZTkxLWIzY2YtZWRlMTUyMWM3MGRjXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", "plot": "Picking up where 'The Suicide Squad' left off, Peacemaker returns home after recovering from his encounter with Bloodsport.", "director": "N/A", "actors": "John Cena, Danielle Brooks, Freddie Stroma", "genre": "Action, Adventure, Comedy", "runtime": "40 min", "trailer_url": "https://www.youtube.com/embed/_mrr3UNALww" },
    { "imdb_id": "tt1751634", "title": "The Sandman", "year": "2022–", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BYTM0NjZjYjItM2JiYS00NmU5LWJmMTMtZjQ0OWU3MWRkNzVmXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_SX300.jpg", "plot": "Upon escaping after decades of imprisonment by a mortal wizard, Dream, the personification of dreams, sets about to reclaim his lost equipment.", "director": "N/A", "actors": "Tom Sturridge, Boyd Holbrook, Patton Oswalt", "genre": "Drama, Fantasy, Horror", "runtime": "45 min", "trailer_url": "https://www.youtube.com/embed/83ClbRPRDXU" },
    { "imdb_id": "tt11192306", "title": "Superman & Lois", "year": "2021–2024", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BOTA2MDVhMWItNTYwYi00OTcyLWE0YjEtM2I5ODVjYjA2YTEyXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg", "plot": "Follow the world's most famous superhero and comic books' most famous journalist as they deal with all the stress, pressures, and complexities that come with being working parents in today's society.", "director": "N/A", "actors": "Tyler Hoechlin, Elizabeth Tulloch, Alex Garfin", "genre": "Action, Adventure, Drama", "runtime": "42 min", "trailer_url": "https://www.youtube.com/embed/z9fCg_O5_2E" },
    { "imdb_id": "tt4016454", "title": "Supergirl", "year": "2015–2021", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BODQ0MzA2Y2YtMWE4MS00YTQ2LWIzM2ItODZkZjE4MWIzODhmXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg", "plot": "The adventures of Superman's cousin in her own superhero career.", "director": "N/A", "actors": "Melissa Benoist, Chyler Leigh, David Harewood", "genre": "Action, Adventure, Drama", "runtime": "43 min", "trailer_url": "https://www.youtube.com/embed/MhD2_j9I9N8" },
    { "imdb_id": "tt4532368", "title": "DC's Legends of Tomorrow", "year": "2016–2022", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BMTYwOTYwOTcwMF5BMl5BanBnXkFtZTgwNTYxMDA3NDE@._V1_SX300.jpg", "plot": "Time-travelling rogue Rip Hunter has to recruit a rag-tag team of heroes and villains to help prevent an apocalypse that could impact not only Earth, but all of time.", "director": "N/A", "actors": "Caity Lotz, Amy Louise Pemberton, Dominic Purcell", "genre": "Action, Adventure, Drama", "runtime": "42 min", "trailer_url": "https://www.youtube.com/embed/4MubNoWQiSc" },

    // 10 Drama Korea
    { "imdb_id": "tt10850932", "title": "Crash Landing on You", "year": "2019–2020", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BMzRiZWZkYmUtYWE2Yi00MDY4LThkMzEtM2M0Y2QxODM5YWI5XkEyXkFqcGdeQXVyNDY5MjMyNTg@._V1_SX300.jpg", "plot": "The absolute top secret love story of a chaebol heiress who made an emergency landing in North Korea...", "director": "N/A", "actors": "Hyun Bin, Son Ye-jin, Seo Ji-hye", "genre": "Comedy, Drama, Romance", "runtime": "85 min", "trailer_url": "https://www.youtube.com/embed/GVwomZf_1pA" },
    { "imdb_id": "tt10919420", "title": "Squid Game", "year": "2021–", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzNjkwZjQzXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg", "plot": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits...", "director": "N/A", "actors": "Lee Jung-jae, Park Hae-soo, Wi Ha-joon", "genre": "Action, Drama, Mystery", "runtime": "55 min", "trailer_url": "https://www.youtube.com/embed/oqxAJKy0ii4" },
    { "imdb_id": "tt12885634", "title": "Vincenzo", "year": "2021", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BODQxM2U2N2YtMzJhMi00Y2YxLThjY2YtMzYwYjEwYmYyMjQyXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg", "plot": "During a visit to his motherland, a Korean-Italian mafia lawyer gives an unrivaled conglomerate a taste of its own medicine...", "director": "N/A", "actors": "Song Joong-ki, Jeon Yeo-been, Taecyeon", "genre": "Comedy, Crime, Drama", "runtime": "80 min", "trailer_url": "https://www.youtube.com/embed/S12-4mXCNj4" },
    { "imdb_id": "tt11239552", "title": "Itaewon Class", "year": "2020", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BODRkMGE0M2YtM2YyMy00YjYyLThkYWMtODRhZDM5NGYxZWRmXkEyXkFqcGdeQXVyNDY5MjMyNTg@._V1_SX300.jpg", "plot": "An ex-con and his friends fight to make their ambitious dreams for their street bar a reality.", "director": "N/A", "actors": "Park Seo-joon, Kim Da-mi, Yoo Jae-myung", "genre": "Drama, Romance", "runtime": "60 min", "trailer_url": "https://www.youtube.com/embed/xgsyq_r-pVM" },
    { "imdb_id": "tt6611916", "title": "Kingdom", "year": "2019–", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BNGMyZTEwY2EtZGFhNS00ZjU2LWI0ZTctNjFkYmFjMDc2ZWMxXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg", "plot": "While strange rumors about their ill king grip a kingdom, the crown prince becomes their only hope...", "director": "N/A", "actors": "Ju Ji-hoon, Bae Doona, Kim Sungkyu", "genre": "Action, Drama, Horror", "runtime": "45 min", "trailer_url": "https://www.youtube.com/embed/4l-yByZPAaA" },
    { "imdb_id": "tt21344706", "title": "The Glory", "year": "2022–2023", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BODQyMDY2NTctOTk4My00MWVjLTgwZGYtN2MyZDBjYTIwNzQxXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg", "plot": "A woman lives for absolute revenge against the childhood bullies who destroyed her life.", "director": "N/A", "actors": "Song Hye-kyo, Lee Do-hyun, Lim Ji-yeon", "genre": "Drama, Thriller", "runtime": "N/A", "trailer_url": "https://www.youtube.com/embed/M_PzVzB3z_k" },
    { "imdb_id": "tt20869502", "title": "Extraordinary Attorney Woo", "year": "2022", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BMDI2MmM1ODUtM2M2My00ZDRiLTk5YjYtYzYzNGE5YjI3MzA4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "plot": "About a 27-year-old lawyer with Asperger's syndrome. Due to her high IQ of 164, impressive memory, and creative thought process...", "director": "N/A", "actors": "Park Eun-bin, Kang Tae-oh, Kang Ki-young", "genre": "Comedy, Drama", "runtime": "70 min", "trailer_url": "https://www.youtube.com/embed/26-7z2zwA8g" },
    { "imdb_id": "tt5994364", "title": "Guardian: The Lonely and Great God", "year": "2016–2017", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BZTg0YmQxZTgtMzM1YS00MTg3LWE2MDYtMTg5YmY4MDk3N2VmXkEyXkFqcGdeQXVyMzE4MDkyNTA@._V1_SX300.jpg", "plot": "In his quest for a bride to break his immortal curse, a 939-year-old guardian of souls meets a grim reaper...", "director": "N/A", "actors": "Gong Yoo, Kim Go-eun, Lee Dong-wook", "genre": "Comedy, Drama, Fantasy", "runtime": "82 min", "trailer_url": "https://www.youtube.com/embed/8AcNEe_7Lw0" },
    { "imdb_id": "tt5500138", "title": "Descendants of the Sun", "year": "2016", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BODRiYjRjMDYtMjJjMS00M2YyLTg5YjYtYzYzNGE5YjI3MzA4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "plot": "A love story develops between Captain Yoo Shi Jin, from Korean Special Forces, and Doctor Kang Mo Yeon...", "director": "N/A", "actors": "Song Joong-ki, Song Hye-kyo, Jin Goo", "genre": "Action, Comedy, Drama", "runtime": "60 min", "trailer_url": "https://www.youtube.com/embed/wk_e2M7iXzI" },
    { "imdb_id": "tt12451520", "title": "It's Okay to Not Be Okay", "year": "2020", "type": "series", "poster": "https://m.media-amazon.com/images/M/MV5BYTk0ZGE1YjItYWM4Yy00OWY2LWE1ZTItZmYxODY0NTMyYjdiXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg", "plot": "An extraordinary road to emotional healing opens up for an antisocial children's book writer and a selfless psych ward caretaker...", "director": "N/A", "actors": "Kim Soo-hyun, Seo Ye-ji, Oh Jung-se", "genre": "Comedy, Drama, Romance", "runtime": "75 min", "trailer_url": "https://www.youtube.com/embed/A0i_1Qc5d_Q" },

];


const importData = async () => {
    try {
        console.log('Memulai proses seeding...');

        // Hapus data yang sudah ada
        console.log('Menghapus data lama...');
        await sql`DELETE FROM movies`;
        await sql`DELETE FROM users`;
        console.log('Data lama berhasil dihapus.');

        // Hash password admin
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(adminUser.password, salt);

        // Buat user admin baru
        console.log('Membuat user admin...');
        await sql`INSERT INTO users (username, password) VALUES (${adminUser.username}, ${hashedPassword})`;
        console.log('User admin berhasil dibuat.');

        // Masukkan data film dan series
        console.log('Mengimpor data konten...');
        // Pastikan nama kolom di sini sama persis dengan di kueri CREATE TABLE (termasuk huruf besar)
        await sql`INSERT INTO movies ${sql(moviesData, 'title', 'year', 'imdb_id', 'type', 'poster', 'plot', 'director', 'actors', 'genre', 'runtime', 'trailer_url')}`;
        console.log(`${moviesData.length} konten berhasil diimpor.`);
        
        console.log('\nSeeding selesai!');
        await sql.end(); // Tutup koneksi database
    } catch (error) {
        console.error(`\nError saat seeding: ${error}`);
        await sql.end();
        process.exit(1);
    }
};

importData();